FROM node:20-alpine AS dependencies

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci


FROM node:20-alpine AS builder

WORKDIR /app

COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_API_PATH_PREFIX=api
ARG NEXT_PUBLIC_API_TIMEOUT_MS=20000
ARG NEXT_PUBLIC_API_WITH_CREDENTIALS=true
ARG NEXT_PUBLIC_API_DEBUG=false
ARG NEXT_PUBLIC_MATCHES_API_BASE_URL
ARG NEXT_PUBLIC_MATCHES_API_PATH
ARG NEXT_PUBLIC_LIVE_SOCKET_URL

ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_API_PATH_PREFIX=$NEXT_PUBLIC_API_PATH_PREFIX
ENV NEXT_PUBLIC_API_TIMEOUT_MS=$NEXT_PUBLIC_API_TIMEOUT_MS
ENV NEXT_PUBLIC_API_WITH_CREDENTIALS=$NEXT_PUBLIC_API_WITH_CREDENTIALS
ENV NEXT_PUBLIC_API_DEBUG=$NEXT_PUBLIC_API_DEBUG
ENV NEXT_PUBLIC_MATCHES_API_BASE_URL=$NEXT_PUBLIC_MATCHES_API_BASE_URL
ENV NEXT_PUBLIC_MATCHES_API_PATH=$NEXT_PUBLIC_MATCHES_API_PATH
ENV NEXT_PUBLIC_LIVE_SOCKET_URL=$NEXT_PUBLIC_LIVE_SOCKET_URL
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build


FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs \
    && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000

CMD ["node", "server.js"]